server:
  port: 9080
spring.application.name: api-traditional
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: zxcvbnm
    hikari:
      maximum-pool-size: 32
  jpa:
    hibernate:
      ddl-auto: none
