chaos:
  monkey:
    enabled: true
    watcher:
      service: true
      rest-controller: false
    assaults:
      latency-active: true
      level: 500
      deterministic: true
      exceptions-active: false
      exception:
        type: studio.camelcase.meetup.exceptions.PersonControllerException
        arguments:
          - type: java.lang.String
            value: Simulated Error

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,chaosmonkey
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true