server:
  port: 9081
spring.application.name: api-vthreads
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
spring:
  threads:
    virtual:
      enabled: true

# OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf;OTEL_LOGS_EXPORTER=none;OTEL_METRICS_EXPORTER=none;OTEL_TRACES_EXPORTER=otlp;OTEL_SERVICE_NAME=traditional-api