version: '3'
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - '3000:3000'
    extra_hosts:
      - host.docker.internal:host-gateway

  prometheus:
    image: prom/prometheus
    container_name: prom
    ports:
      - '9090:9090'
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - './prom/prom.yml:/etc/prometheus/prometheus.yml'

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: '9411'
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
      - '4318:4318'
      - '4317:4317'

  db-legacy:
    image: postgres:16-alpine
    container_name: db-legacy
    environment:
      POSTGRES_DB: customer
      POSTGRES_PASSWORD: zxcvbnm
    ports:
      - '15432:5432'

  db-vthreads:
    image: postgres:16-alpine
    container_name: db-vthreads
    environment:
      POSTGRES_DB: customer
      POSTGRES_PASSWORD: asdfghjkl
    ports:
      - '25432:5432'

  flyway:
    image: flyway/flyway
    container_name: db-migration
    volumes:
      - './flyway/config/legacy.conf:/flyway/conf/flyway.conf'
#      - './flyway/config/vthreads.conf:/flyway/conf/flyway.conf'
      - './flyway/db_migration/:/flyway/sql'
    extra_hosts:
      - host.docker.internal:host-gateway